"""toll plaza internet sync (toll_plazas.place, state_name, source key; toll_plaza_sync_runs)

Adds place and state-as-in-source to toll_plazas, a unique key (api_source, external_plaza_id), and
toll_plaza_sync_runs — the history of fetches from OpenStreetMap / data.gov.in / FASTag APIs.

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-30 05:16:11.543380
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('toll_plaza_sync_runs',
    sa.Column('integration_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('states', sa.String(length=255), nullable=True),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('states_done', sa.Integer(), nullable=False),
    sa.Column('states_total', sa.Integer(), nullable=False),
    sa.Column('fetched', sa.Integer(), nullable=False),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('unchanged', sa.Integer(), nullable=False),
    sa.Column('skipped', sa.Integer(), nullable=False),
    sa.Column('skipped_samples', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('triggered_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['toll_api_configurations.id'], name=op.f('fk_toll_plaza_sync_runs_integration_id_toll_api_configurations')),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], name=op.f('fk_toll_plaza_sync_runs_triggered_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_toll_plaza_sync_runs'))
    )
    op.create_index(op.f('ix_toll_plaza_sync_runs_integration_id'), 'toll_plaza_sync_runs', ['integration_id'], unique=False)
    op.create_index(op.f('ix_toll_plaza_sync_runs_started_at'), 'toll_plaza_sync_runs', ['started_at'], unique=False)
    op.create_index(op.f('ix_toll_plaza_sync_runs_status'), 'toll_plaza_sync_runs', ['status'], unique=False)
    op.create_index(op.f('ix_toll_plaza_sync_runs_triggered_by'), 'toll_plaza_sync_runs', ['triggered_by'], unique=False)
    op.add_column('toll_plazas', sa.Column('place', sa.String(length=150), nullable=True))
    op.add_column('toll_plazas', sa.Column('state_name', sa.String(length=100), nullable=True))
    op.create_unique_constraint('uq_toll_plaza_source_ext', 'toll_plazas', ['api_source', 'external_plaza_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_constraint('uq_toll_plaza_source_ext', 'toll_plazas', type_='unique')
    op.drop_column('toll_plazas', 'state_name')
    op.drop_column('toll_plazas', 'place')
    op.drop_table('toll_plaza_sync_runs')  # its indexes go with it (dropping them first breaks MySQL FK rules)
