"""Interactive helper used by run_app.bat / run_app.sh: writes a development .env file.

Asks for the MySQL connection, URL-encodes the password, generates a random secret key and
sets values suitable for running on http://localhost (cookie_secure=false).
"""
from __future__ import annotations

import getpass
import secrets
import sys
from pathlib import Path
from urllib.parse import quote_plus

ROOT = Path(__file__).resolve().parent.parent
ENV = ROOT / ".env"


def ask(prompt: str, default: str) -> str:
    v = input(f"{prompt} [{default}]: ").strip()
    return v or default


def main() -> None:
    if ENV.exists() and "--force" not in sys.argv:
        print(".env already exists - keeping it.")
        return
    print()
    print("=== TRANS ERP - first-time settings (saved to .env) ===")
    print("Enter the MySQL connection. The database ERP_LOGISTICS is created automatically.")
    host = ask("MySQL host", "127.0.0.1")
    port = ask("MySQL port", "3306")
    user = ask("MySQL user", "root")
    pw = getpass.getpass("MySQL password (hidden): ")
    db = ask("Database name", "ERP_LOGISTICS")
    url = f"mysql+pymysql://{quote_plus(user)}:{quote_plus(pw)}@{host}:{port}/{db}?charset=utf8mb4"
    ENV.write_text("\n".join([
        "# Generated by scripts/make_env.py - edit as needed (see .env.example for all options)",
        "ERP_ENV=development",
        "ERP_APP_NAME=TRANS ERP",
        "ERP_COMPANY_NAME=Transport & Logistics",
        f"ERP_DATABASE_URL={url}",
        f"ERP_SECRET_KEY={secrets.token_urlsafe(48)}",
        "ERP_COOKIE_SECURE=false",
        "ERP_TIMEZONE=Asia/Kolkata",
        "ERP_STORAGE_DIR=storage",
        "ERP_LOG_DIR=logs",
        "",
    ]), encoding="utf-8")
    print(f"Saved {ENV}")


def check_db() -> int:
    """Exit code 0 if the MySQL server in .env is reachable, else print the reason and return 1."""
    from sqlalchemy import create_engine, text
    from sqlalchemy.engine import URL, make_url
    from app.config import get_settings
    u = make_url(get_settings().database_url)
    server = URL.create(u.drivername, username=u.username, password=u.password, host=u.host, port=u.port, query=u.query)
    try:
        with create_engine(server).connect() as c:
            c.execute(text("SELECT 1"))
        return 0
    except Exception as exc:  # noqa: BLE001
        print(f"\nCannot connect to MySQL at {u.host}:{u.port} as '{u.username}':\n  {getattr(exc, 'orig', exc)}")
        print("Check that the MySQL service is running and the user/password are right.")
        print("To re-enter the settings, delete the .env file and start again.")
        return 1


if __name__ == "__main__":
    sys.path.insert(0, str(ROOT))
    if "--check-db" in sys.argv:
        sys.exit(check_db())
    main()
